"""create calibration table

Revision ID: 29127f71126c
Revises: fe1fff947a44
Create Date: 2026-04-01 05:14:44.338802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29127f71126c'
down_revision: Union[str, None] = 'fe1fff947a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gaze_x', sa.Float(), nullable=False),
    sa.Column('gaze_y', sa.Float(), nullable=False),
    sa.Column('screen_x', sa.Integer(), nullable=False),
    sa.Column('screen_y', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(),nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_points_id'), 'calibration_points', ['id'], unique=False)
    op.create_index(op.f('ix_calibration_points_user_id'), 'calibration_points', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calibration_points_user_id'), table_name='calibration_points')
    op.drop_index(op.f('ix_calibration_points_id'), table_name='calibration_points')
    op.drop_table('calibration_points')
    # ### end Alembic commands ###
