"""add reset_email_sent to admin

Revision ID: 615683abaf52
Revises: f95be7dcfea5
Create Date: 2026-04-04 20:52:09.691414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615683abaf52'
down_revision: Union[str, None] = 'f95be7dcfea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('reset_email_sent', sa.Boolean(), nullable=True))
    op.alter_column('admin', 'must_reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'must_reset_password',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('admin', 'reset_email_sent')
    # ### end Alembic commands ###
