"""add report_url for recommendation_model

Revision ID: af0b42568285
Revises: df4c788f003e
Create Date: 2026-04-11 12:27:36.414277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af0b42568285'
down_revision: Union[str, None] = 'df4c788f003e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('report_url', sa.String(), nullable=True))
    op.alter_column('recommendations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               existing_nullable=False)
    op.alter_column('user_actions', 'action',
               existing_type=postgresql.ENUM('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               type_=sa.Enum('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_actions', 'action',
               existing_type=sa.Enum('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               type_=postgresql.ENUM('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               existing_nullable=False)
    op.alter_column('recommendations', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               existing_nullable=False)
    op.drop_column('recommendations', 'report_url')
    # ### end Alembic commands ###
