"""add status to devices

Revision ID: b56380346d70
Revises: d7728fd4e11a
Create Date: 2026-05-10 07:27:03.707911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56380346d70'
down_revision: Union[str, None] = 'd7728fd4e11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('status', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('accessibility_features', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'accessibility_features')
    op.drop_column('devices', 'status')
    # ### end Alembic commands ###
