"""make recommendation table

Revision ID: df4c788f003e
Revises: cd9563291c91
Create Date: 2026-04-06 03:36:11.499996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df4c788f003e'
down_revision: Union[str, None] = 'cd9563291c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user_actions', 'action',
               existing_type=postgresql.ENUM('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               type_=sa.Enum('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               existing_nullable=False)
    op.drop_index('ix_user_actions_device_id', table_name='user_actions')
    op.drop_index('ix_user_actions_user_id', table_name='user_actions')
    op.drop_index('ix_user_device_time', table_name='user_actions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_device_time', 'user_actions', ['user_id', 'device_id', 'timestamp'], unique=False)
    op.create_index('ix_user_actions_user_id', 'user_actions', ['user_id'], unique=False)
    op.create_index('ix_user_actions_device_id', 'user_actions', ['device_id'], unique=False)
    op.alter_column('user_actions', 'action',
               existing_type=sa.Enum('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               type_=postgresql.ENUM('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               existing_nullable=False)
    op.drop_table('recommendations')
    # ### end Alembic commands ###
