"""make 'email' is index and remove index from 'id' into admin

Revision ID: 0f078b69b1d7
Revises: 80d2e48685c2
Create Date: 2026-04-03 03:34:05.473811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f078b69b1d7'
down_revision: Union[str, None] = '80d2e48685c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_email', table_name='admin')
    op.drop_index('ix_admin_id', table_name='admin')
    op.create_unique_constraint("uq_admin_email", 'admin', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_admin_email", 'admin', type_='unique')
    op.create_index('ix_admin_id', 'admin', ['id'], unique=True)
    op.create_index('ix_admin_email', 'admin', ['email'], unique=True)
    # ### end Alembic commands ###
