"""fix somethings into RecommnedationModel

Revision ID: 1ddc00f009fc
Revises: af0b42568285
Create Date: 2026-04-11 20:28:55.725440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ddc00f009fc'
down_revision: Union[str, None] = 'af0b42568285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('device_id', sa.UUID(), nullable=False))
    op.alter_column('recommendations', 'time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recommendations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               existing_nullable=False)
    op.create_foreign_key(None, 'recommendations', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(None, 'recommendations', 'users', ['user_id'], ['id'])
    op.drop_column('recommendations', 'device')
    op.alter_column('user_actions', 'action',
               existing_type=postgresql.ENUM('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               type_=sa.Enum('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_actions', 'action',
               existing_type=sa.Enum('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               type_=postgresql.ENUM('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               existing_nullable=False)
    op.add_column('recommendations', sa.Column('device', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.alter_column('recommendations', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               existing_nullable=False)
    op.alter_column('recommendations', 'time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('recommendations', 'device_id')
    # ### end Alembic commands ###
