"""using action_type & action_value instead of action

Revision ID: 677d4bb0b6ee
Revises: 1ddc00f009fc
Create Date: 2026-04-11 21:16:17.652521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '677d4bb0b6ee'
down_revision: Union[str, None] = '1ddc00f009fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('action_type', sa.String(), nullable=False))
    op.add_column('recommendations', sa.Column('action_value', sa.Integer(), nullable=True))
    op.alter_column('recommendations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               existing_nullable=False)
    op.drop_column('recommendations', 'action')
    op.alter_column('user_actions', 'action',
               existing_type=postgresql.ENUM('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               type_=sa.Enum('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_actions', 'action',
               existing_type=sa.Enum('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               type_=postgresql.ENUM('ON', 'OFF', 'ADJUST', name='action_type_enum'),
               existing_nullable=False)
    op.add_column('recommendations', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('recommendations', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               existing_nullable=False)
    op.drop_column('recommendations', 'action_value')
    op.drop_column('recommendations', 'action_type')
    # ### end Alembic commands ###
