"""add must_reset_password into admin

Revision ID: f95be7dcfea5
Revises: 0f078b69b1d7
Create Date: 2026-04-03 05:15:08.781617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95be7dcfea5'
down_revision: Union[str, None] = '0f078b69b1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('must_reset_password', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'must_reset_password')
    # ### end Alembic commands ###
